disabled_rules:
  - fallthrough
  - function_parameter_count
  - line_length
  - nesting
  - operator_whitespace
  - todo
  - trailing_whitespace
  - identifier_name
included:
  - Adyen
  - AdyenCard
  - AdyenInternal
  - AdyenSEPA
  - AdyenApplePay
  - AdyenTests
  - AdyenUITests
  - AdyenUIHost
excluded:
  - Pods
